### ISSUE TITLE
데이터 질에 대한 의문점

### ISSUE THREAD

**Issue by nila27** [Gumball12/malicious-url-detection#1]
65만여 개의 데이터로는 학습하기에 많은 양은 아닌데

해당 데이터들의 질도 별로 좋지 않다고 생각함.

예를 들어, malware의 http://9779.info로 시작하는 url은 그냥 malware url로 때려도 될 것 같은데 그러면 약 4000개의 데이터가 버려짐.

url 만으로는 유의미한 결과를 뽑기 힘들 것 같으니 최소한 ip 주소부터, 피싱 같은 것은 열고 닫아버릴테니 열린 날짜 등 더 데이터들이 필요하지 않을가 싶음.

**Comment by Gumball12** [comment]
@nila27 
언급하신 것과 같이 호스트가 특정 케이스로 판정된 경우, 관련 URL은 모두 동일하게 처리하는 방식이 더 효율적입니다.
향후 조금 더 공부할 시간이 주어진다면 말씀해주신 내용 포함해 개선하도록 하겠습니다.
피드백 감사드립니다.

**Comment by nila27** [comment]
https://www.kaggle.com/search?q=url+in%3Adatasets

여기에 데이터 셋 많으니 시간 나면 함 보셈

**Comment by Gumball12** [comment]
감사합니다 🙂

**Comment by nila27** [comment]
고마우면 이모티콘 말고 콘

**Comment by Gumball12** [comment]
@nila27 
![image](https://user-images.githubusercontent.com/28308362/173484830-0391e3e4-4da1-4baf-b6c9-47087447a225.png)
